# Copyright (c) 2017-present Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (c) 2017-present Sven Greb <code@svengreb.de>

# Project:    Nord Alacritty
# Version:    0.1.0
# Repository: https://github.com/arcticicestudio/nord-alacritty
# License:    MIT
# References:
#   https://github.com/alacritty/alacritty
env:
  TERM: alacritty
  COLORTERM: truecolor
window:
  opacity: 0.90
  padding:
   x: 12
   y: 12

colors:
  primary:
    background: '#282c34'
    foreground: '#abb2bf'
  cursor:
    text:       CellBackground
  selection:
    text:       CellForeground
    background: '#3e4451' # syntax-selection-color
  normal:
    black:      '#5c6370' # mono-3
    red:        '#e06c75' # red 1
    green:      '#98c379'
    yellow:     '#e5c07b' # orange 2
    blue:       '#61afef'
    magenta:    '#c678dd'
    cyan:       '#56b6c2'
    white:      '#828997' # mono-2

font:
  normal:
    #family: Monocraft
    family: JetBrains Mono Nerd Font
    #family: Fira Code Nerd FontMono
    style: Regular

  bold:
    family: JetBrains Mono Nerd Font
    style: Bold

  italic:
    family: JetBrains Mono Nerd Font
    style: Italic

  bold_italic:
    family: JetBrains Mono Nerd Font
    style: Bold Italic

  size: 11
