# Copyright (c) 2017-present Arctic Ice Studio <development@arcticicestudio.com>
# Copyright (c) 2017-present Sven Greb <code@svengreb.de>

# Project:    Nord Alacritty
# Version:    0.1.0
# Repository: https://github.com/arcticicestudio/nord-alacritty
# License:    MIT
# References:
#   https://github.com/alacritty/alacritty
env:
  TERM: alacritty
  COLORTERM: truecolor
window:
  opacity: 1
  padding:
    x: 12
    y: 12

colors:
  # Default colors
  primary:
    background: '#0A0E14'
    foreground: '#B3B1AD'

  # Normal colors
  normal:
    black: '#01060E'
    red: '#EA6C73'
    green: '#91B362'
    yellow: '#F9AF4F'
    blue: '#53BDFA'
    magenta: '#FAE994'
    cyan: '#90E1C6'
    white: '#C7C7C7'

  # Bright colors
  bright:
    black: '#686868'
    red: '#F07178'
    green: '#C2D94C'
    yellow: '#FFB454'
    blue: '#59C2FF'
    magenta: '#FFEE99'
    cyan: '#95E6CB'
    white: '#FFFFFF'

font:
  normal:
    #family: Monocraft
    family: JetBrains Mono Nerd Font
    #family: Fira Code Nerd FontMono
    style: Regular

  bold:
    family: JetBrains Mono Nerd Font
    style: Bold

  italic:
    family: JetBrains Mono Nerd Font
    style: Italic

  bold_italic:
    family: JetBrains Mono Nerd Font
    style: Bold Italic

  size: 11
theme: Ayu-Dark
